# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kkhabour <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/03/29 17:16:16 by kkhabour          #+#    #+#              #
#    Updated: 2019/03/30 18:59:40 by kkhabour         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
FLAGS = -Wall -Wextra -Werror

all:
	gcc $(FLAGS) -o $(NAME) $(NAME).c
clean:
	rm -f *.o
fclean: clean
	rm -f $(NAME)
